Add files via upload
Orbital Assault
Error: Terminators gain Deep Strike
FIXED: Added to Terminators Category
    
Error: Must have Deep Strike tag, or have at least as many Vehicles with Deep Strike tag as it has Infantry that does not have Deep Strike tag
NOT FIXABLE: Due to BS limitations it makes it undoable as multiple units could for instance go in a Thunderhawk. So must be checked by players

----
Armoured Spearhead
Error: All units must take DT - no more units then vehicles with transcap
NOT FIXABLE: Due to BS limitations must be checked by player.

----
Brethren of Iron
Error: No more Automanta then units with LA
FIXED: Added new category

Error: No Paragon of Metal
FIXED: Changed link for Vorax

----
Outcast Sons
Error: More troops then Elites
FIXED: Same as some of the other ones above.

----
Sky hunter Phalanx
Error: Infantry must be mounted in flyers/Skimmers
NOT FIXABLE: Again issue of limitations of lots of variables.

Error: Otherwise, only jetbikes
NOT FIXABLE: Again issue of limitations of lots of variables.

----
Orphans of Betrayal
Error: More Troops then HS
FIXED: Same as some of the other ones above.

----
Drop Assault Vanguard
Error: Deep strikers or embarked on flyers only
NOT FIXABLE: Again issue of limitations of lots of variables.

----
Legion Recon Company
Error: must include additional compulsory legion recon squad
FIXED: Added a min requirement of 1 to the unit from Troops selection.

Error: Units limited to 15 marines at most.
FIXED: Added limitation on assault, breacher, immortals, phalanx, tacticals.

----
Sacrificial offering:
Error: Must Include Allied Militia detachment
NOT YET FIXABLE: This issue requires a huge rework.

Error: No units with Immobile or Slow and Purposeful rules
FIXED: Added to restricted list

No models that deploy via Deep Strike
NOT FIXABLE: Again issue of limitations of lots of variables.