Updates and fixes for rules and restrictions.
Hammerfall Strikeforce
The Stone Gauntlet:
Error: Cannot take more Elites and Fast Attack choices in total than Troop choices
FIXED - And I'm sure some Imp fist players are gunna hate that 😃

Sons of Horus
The Black Reaving
FIXED - Must take more Fast attack then Heavy Support
FIXED - +1 compulsory troop (3+ instead of 2+)

Salamanders
The Covenant of Fire
Hopefully fixed (might be some exceptions) - All Meltaguns, Inferno Pistols, and Multi-Meltas are Master-Crafted
Hopefully fixed (might be some exceptions) - All Vehicles have a 5++ vs Melta, Volkite, Plasma, and flamer weapons, and also against meltabombs
FIXED - All units gain Move through cover
FIXED - May not take more HS AND FA then total of Troops