ROW Fixes Angels, PotL, ArmBreak, PrimChosen
Angel's Wrath
Error: Jump Infantry Gains Hit&Run
FIXED by adding to category

Error: Storm Eagle and Fire Raptors gain Strafing Run
FIXED for Storm Eagle. The Fire Raptor must be a relic ROW thing as they come with it by default in current book.

Also Storm Eagles start without their Vengeance Launcher selected
FIXED all free options are now selected on both versions of the Storm Eagle

Only Units with Jump Infantry, Skimmer, and Jetbike type, as well as infantry that starts inside flyers or skimmers may be chosen as part of this list, with no more infantry then Flyer/Skimmers with transcap
NOT FIXABLE: Sadly that is one of the ones that you can remove some things from the lists, but it has to be manually checked for most as there are to many variables for adding units inside a a land raider which is brought in on a thunderhawk or whatever.

Error: No Tanks (Unless Skimmer/Flyer)
FIXED: Added the category of Non Flyer/Scimmer Vehicle to add of them (even though its tanks, it basically functions the same way, just didn't add it to the walkers and superheavy.

----
Pride of the Legion
Error: More Units with LA then without
FIXED: PotL Requirement Legiones Astartes added to Categories and force entries, linked to Units and Legiones Astartes

----
Armoured Breakthrough
Error: Tanks with 3HP or less gain Fast
FIXED: Added rule and append to profiles.

Error: All infantry units that can do so must be mounted in DT, and there must be greater than or equal to the number of Infantry units without DT options as Transport Vehicles (Tank or SHV)
NOT FIXABLE: Sadly not able to be done again due to limitations of BS.

Error: No more Skimmers then Flyers then it has Tank
FIXED: Added min requirement to tanks repeating based on skimmers and flyers. Also moved skimmer category to land speeder and javelin from unit.

----
Primarch's Chosen
Error: More Units with LA then without
FIXED: Same as PotL fix.